'use server';
import prisma from '@/lib/prisma';
import { getTenantContext } from '@/lib/auth/getTenantContext';
import {
  updateProductSchema, addStockSchema,
  createCustomerSchema,
} from '@/lib/validation/schemas';

// ── Timezone-safe expiry check ────────────────────────────────────────────────
// Compares against start-of-today (UTC midnight) so a product expiring "today"
// is NOT flagged as expired mid-day, regardless of server timezone.
function isExpired(expiryDate: Date): boolean {
  const startOfToday = new Date();
  startOfToday.setUTCHours(0, 0, 0, 0);
  return expiryDate < startOfToday;
}

// ── Products ──────────────────────────────────────────────────────────────────

export async function getProducts(search?: string) {
  const { tenantId } = await getTenantContext();

  return prisma.product.findMany({
    where: {
      tenantId,
      ...(search
        ? { name: { contains: search.toUpperCase() } }
        : { saleItems: { some: {} } }),
    },
    take:    search ? 50 : 20,
    orderBy: [{ saleItems: { _count: 'desc' } }, { name: 'asc' }],
  });
}

export async function updateProduct(id: number, data: { price: number; stockQty: number }) {
  const { tenantId } = await getTenantContext();
  const parsed = updateProductSchema.parse({ id, ...data });

  return prisma.product.update({
    where: { id: parsed.id, tenantId },
    data: { price: parsed.price, stockQty: parsed.stockQty },
  });
}

export async function addStock(id: number, quantity: number) {
  const { tenantId } = await getTenantContext();
  const parsed = addStockSchema.parse({ id, quantity });

  return prisma.product.update({
    where: { id: parsed.id, tenantId },
    data:  { stockQty: { increment: parsed.quantity } },
  });
}

// ── Customers ─────────────────────────────────────────────────────────────────

export async function getCustomers(search?: string) {
  const { tenantId } = await getTenantContext();

  return prisma.customer.findMany({
    where: {
      tenantId,
      ...(search ? {
        OR: [
          { name:  { contains: search } },
          { phone: { contains: search } },
        ],
      } : {}),
    },
    take:    10,
    orderBy: { name: 'asc' },
  });
}

export async function createCustomer(name: string, phone: string) {
  const { tenantId } = await getTenantContext();
  const { name: trimmedName, phone: trimmedPhone } = createCustomerSchema.parse({ name, phone });

  // Check for duplicate phone within tenant
  const existing = await prisma.customer.findFirst({
    where: { phone: trimmedPhone, tenantId },
  });
  if (existing) throw new Error('A customer with this phone number already exists');

  return prisma.customer.create({
    data: { name: trimmedName, phone: trimmedPhone, tenantId },
  });
}

// ── Sales ─────────────────────────────────────────────────────────────────────

export async function processSale(
  items:        { id: number; quantity: number }[],  // price removed — server fetches authoritative price
  customerId?:  number,
  clientToken?: string,                              // idempotency key (UUID generated by client)
  discount?:    number,                              // fixed discount amount
  paymentType?: string,                              // 'Cash' | 'MoMo' | 'Split'
  miscItems?:   { name: string; price: number; quantity: number }[],
) {
  const { tenantId, userId } = await getTenantContext();

  // Basic shape validation
  const hasRegularItems = items.length > 0;
  const hasMiscItems = miscItems && miscItems.length > 0;
  if (!hasRegularItems && !hasMiscItems) throw new Error('Cart is empty');

  if (hasRegularItems && items.some(i => i.quantity < 1 || !Number.isInteger(i.quantity))) {
    throw new Error('Invalid item quantities');
  }

  // Validate payment type
  const validPaymentTypes = ['Cash', 'MoMo', 'Split'];
  const resolvedPaymentType = validPaymentTypes.includes(paymentType ?? '') ? paymentType! : 'Cash';

  // Validate discount
  const resolvedDiscount = typeof discount === 'number' && discount > 0 ? discount : 0;

  // Validate misc items
  const resolvedMiscItems = hasMiscItems
    ? miscItems!.filter(m => m.name && m.price > 0 && m.quantity >= 1)
    : [];
  const miscTotal = resolvedMiscItems.reduce((sum, m) => sum + m.price * m.quantity, 0);

  const sellerId = parseInt(userId, 10);
  if (isNaN(sellerId)) throw new Error('Invalid user session — please log in again');

  // ── Idempotency check: if this clientToken already processed, return early ──
  if (clientToken) {
    const existing = await prisma.sale.findUnique({ where: { clientToken } });
    if (existing) return existing;
  }

  return prisma.$transaction(async (tx) => {
    let serverTotal = 0;
    let productMap = new Map<number, any>();

    if (hasRegularItems) {
      // ── Batch-fetch all products in ONE query (kills N+1) ─────────
      const products = await tx.product.findMany({
        where: { id: { in: items.map(i => i.id) }, tenantId },
      });
      productMap = new Map(products.map(p => [p.id, p]));

      // ── Validate all items before touching stock ──────────────────────────
      for (const item of items) {
        const product = productMap.get(item.id);
        if (!product) throw new Error(`Product not found (ID: ${item.id})`);

        if (product.expiryDate && isExpired(product.expiryDate)) {
          throw new Error(`Cannot sell expired product: ${product.name}`);
        }
        if (product.stockQty < item.quantity) {
          throw new Error(
            `Insufficient stock for ${product.name}: ${product.stockQty} available, ${item.quantity} requested`,
          );
        }
      }

      // ── Server-side pricing — never trust client-supplied price ────
      serverTotal = items.reduce((sum, item) => {
        return sum + productMap.get(item.id)!.price * item.quantity;
      }, 0);
    }

    // Cap discount at gross total
    const grossTotal = serverTotal + miscTotal;
    const cappedDiscount = Math.min(resolvedDiscount, grossTotal);
    const finalTotal = Math.round((grossTotal - cappedDiscount) * 100) / 100;

    // ── Create sale with authoritative server price ───────────────────────
    const sale = await tx.sale.create({
      data: {
        totalAmount: finalTotal,
        discount:    cappedDiscount,
        paymentType: resolvedPaymentType,
        status:      'Completed',
        sellerId,
        tenantId,
        ...(clientToken ? { clientToken } : {}),
        ...(customerId  ? { customerId }  : {}),
        ...(resolvedMiscItems.length > 0 ? { miscItems: JSON.stringify(resolvedMiscItems) } : {}),
        ...(hasRegularItems ? {
          items: {
            create: items.map(item => ({
              productId: item.id,
              quantity:  item.quantity,
              price:     productMap.get(item.id)!.price,
            })),
          },
        } : {}),
      },
    });

    // ── Loyalty points ────────────────────────────────────────────────────
    if (customerId) {
      const points = Math.floor(finalTotal / 10);
      if (points > 0) {
        await tx.customer.update({
          where: { id: customerId },
          data:  { loyaltyPoints: { increment: points } },
        });
      }
    }

    // ── Atomic stock decrement with race condition prevention ────────────
    if (hasRegularItems) {
      for (const item of items) {
        const affected = await tx.product.updateMany({
          where: {
            id:       item.id,
            tenantId,
            stockQty: { gte: item.quantity },
          },
          data: { stockQty: { decrement: item.quantity } },
        });
        if (affected.count === 0) {
          throw new Error(
            `Stock conflict for ${productMap.get(item.id)?.name}: insufficient stock. Please refresh and retry.`,
          );
        }
      }
    }

    return sale;
  });
}

// ── Bulk Import ──────────────────────────────────────────────────────────────

export interface ImportRow {
  name: string;
  price: number;
  costPrice: number;
  stockQty: number;
  expiryDate: string;
  barcode: string;
  category: string;
}

export async function bulkImportProducts(rows: ImportRow[]) {
  const { tenantId, role } = await getTenantContext();

  if (role !== 'MANAGER' && role !== 'SUPER_ADMIN') {
    throw new Error('Only managers can import products');
  }
  if (!rows.length) throw new Error('No products to import');
  if (rows.length > 5000) throw new Error('Maximum 5,000 products per import');

  let created = 0;
  let skipped = 0;
  const errors: string[] = [];

  // Process in batches of 50 to avoid overwhelming the DB
  for (let i = 0; i < rows.length; i += 50) {
    const batch = rows.slice(i, i + 50);

    for (const row of batch) {
      try {
        const name = (row.name || '').trim().toUpperCase();
        if (!name) { skipped++; continue; }

        const price    = Math.max(0, Number(row.price) || 0);
        const costPrice = Number(row.costPrice) || null;
        const stockQty = Math.max(0, Math.floor(Number(row.stockQty) || 0));
        const category = (row.category || 'General').trim();
        const barcode  = (row.barcode || '').trim() || null;

        let expiryDate: Date | null = null;
        if (row.expiryDate) {
          const d = new Date(row.expiryDate);
          if (!isNaN(d.getTime())) expiryDate = d;
        }

        // Skip if exact same name already exists for this tenant
        const existing = await prisma.product.findFirst({
          where: { name, tenantId },
        });
        if (existing) { skipped++; continue; }

        await prisma.product.create({
          data: {
            name, price, costPrice, stockQty,
            expiryDate, category, tenantId,
            description: barcode ? `Barcode: ${barcode}` : null,
          },
        });
        created++;
      } catch (err: any) {
        errors.push(`Row "${row.name}": ${err.message}`);
      }
    }
  }

  return { created, skipped, errors: errors.slice(0, 20), total: rows.length };
}

// ── Tenant Info ───────────────────────────────────────────────────────────────

export async function getTenantInfo() {
  const { tenantId } = await getTenantContext();

  const tenant = await prisma.tenant.findUnique({
    where: { id: tenantId },
    select: { name: true, address: true, primaryPhone: true, primaryEmail: true },
  });

  return tenant ?? { name: 'Pharmacy', address: '', primaryPhone: '', primaryEmail: '' };
}
